version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: integracao_logistica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: